namespace SpriteKind {
    export const Shark = SpriteKind.create()
    export const EnemyProjectile = SpriteKind.create()
}

namespace shark {

    let boss:Sprite = null
    let bossInvulnerable = false;
    let playerSprite:Sprite = null;
    const SHARK_MAX_HP = 100

    export function spawnBoss (_playerSprite : Sprite, initHandler:boolean) {
        boss = sprites.create(img`
            .............ccfff..............
            ...........ccddbcf..............
            ..........ccddbbf...............
            ..........fccbbcf...............
            .....fffffccccccff.........ccc..
            ...ffbbbbbbbcbbbbcfff....ccbbc..
            ..fbbbbbbbbcbcbbbbcccff.cdbbc...
            ffbbbbbbffbbcbcbbbcccccfcdbbf...
            fbcbbb11ff1bcbbbbbcccccffbbf....
            fbbb11111111bbbbbcccccccbbcf....
            .fb11133cc11bbbbcccccccccccf....
            ..fccc31c111bbbcccccbdbffbbcf...
            ...fc13c111cbbbfcddddcc..fbbf...
            ....fccc111fbdbbccdcc.....fbbf..
            ........ccccfcdbbcc........fff..
            .............fffff..............
            `, SpriteKind.Shark)
        bossNormalAnimation()
        boss.setPosition(140, randint(10, 110))
        boss.setVelocity(30, 30)
        sprites.setDataNumber(boss, "hp", SHARK_MAX_HP)
        cubicbird.displayHitPointBar(sprites.readDataNumber(boss, "hp") / SHARK_MAX_HP * 100)

        playerSprite = _playerSprite

        if (initHandler) {
            game.onUpdate(function () {
            if (boss) {
                moveBoss()
            }
            })
            game.onUpdateInterval(2000, function () {
                if (boss) {
                    bossAttackAnimation()
                    bossAttack()
                }
            })
        }
    }

    function bossAttack () {
        let teethSprite = sprites.createProjectileFromSprite(img`
            ....................................
            ....................................
            ....................................
            ............111.....................
            ...........11111....................
            ..........1cccc11...................
            ...........c1c1c1...................
            ............c3331...................
            ...........c333c1...................
            ...........c331c11..................
            ..........cc13c111..................
            ..........c111111...................
            ...........cc1111...................
            .............ccc....................
            ....................................
            ....................................
            `, boss, -80, 0)
        teethSprite.setKind(SpriteKind.EnemyProjectile)
    }

    function bossNormalAnimation () {
        animation.runImageAnimation(
        boss,
        [img`
            .............ccfff..............
            ...........ccddbcf..............
            ..........ccddbbf...............
            ..........fccbbcf...............
            .....fffffccccccff.........ccc..
            ...ffbbbbbbbcbbbbcfff....ccbbc..
            ..fbbbbbbbbcbcbbbbcccff.cdbbc...
            ffbbbbbbffbbcbcbbbcccccfcdbbf...
            fbcbbb11ff1bcbbbbbcccccffbbf....
            fbbb11111111bbbbbcccccccbbcf....
            .fb11133cc11bbbbcccccccccccf....
            ..fccc31c111bbbcccccbdbffbbcf...
            ...fc13c111cbbbfcddddcc..fbbf...
            ....fccc111fbdbbccdcc.....fbbf..
            ........ccccfcdbbcc........fff..
            .............fffff..............
            `,img`
            .............ccfff..............
            ............cddbbf..............
            ...........cddbbf...............
            ..........fccbbcf............ccc
            ....ffffffccccccff.........ccbbc
            ..ffbbbbbbbbbbbbbcfff.....cdbbc.
            ffbbbbbbbbbcbcbbbbcccff..cddbbf.
            fbcbbbbbffbbcbcbbbcccccfffdbbf..
            fbbb1111ff1bcbcbbbcccccccbbbcf..
            .fb11111111bbbbbbcccccccccbccf..
            ..fccc33cc11bbbbccccccccfffbbcf.
            ...fc131c111bbbcccccbdbc...fbbf.
            ....f33c111cbbbfdddddcc.....fbbf
            .....ff1111fbdbbfddcc........fff
            .......cccccfbdbbfc.............
            .............fffff..............
            `,img`
            ..............cfff..............
            ............ccddbf..............
            ...........cbddbff.........ccc..
            ..........fccbbcf.........cbbc..
            ...fffffffccccccff.......cdbc...
            .ffcbbbbbbbbbbbbbcfff....cdbf...
            fcbbbbbbbbbcbbbbbbcccff.cdbf....
            fbcbbbbffbbbcbcbbbcccccffdcf....
            fbb1111ffbbbcbcbbbccccccbbcf....
            .fb11111111bbcbbbccccccccbbcf...
            ..fccc33cb11bbbbcccccccfffbbf...
            ...fc131c111bbbcccccbdbc..fbbf..
            ....f33c111cbbccdddddbc....fff..
            .....ff1111fdbbccddbcc..........
            .......cccccfdbbbfcc............
            .............fffff..............
            `,img`
            .............ccfff..............
            ............cddbbf..............
            ...........cddbbf...............
            ..........fccbbcf............ccc
            ....ffffffccccccff.........ccbbc
            ..ffbbbbbbbbbbbbbcfff.....cdbbc.
            ffbbbbbbbbbcbcbbbbcccff..cddbbf.
            fbcbbbbbffbbcbcbbbcccccfffdbbf..
            fbbb1111ff1bcbcbbbcccccccbbbcf..
            .fb11111111bbbbbbcccccccccbccf..
            ..fccc33cc11bbbbccccccccfffbbcf.
            ...fc131c111bbbcccccbdbc...fbbf.
            ....f33c111cbbbfdddddcc.....fbbf
            .....ff1111fbdbbfddcc........fff
            .......cccccfbdbbfc.............
            .............fffff..............
            `],
        200,
        true
        )
    }

    function moveBoss () {
        if (boss.x > 150) {
            boss.vx = -30
        }
        if (boss.x < 40) {
            boss.vx = 30
        }
        if (boss.y > 110) {
            boss.vy = -30
        }
        if (boss.y < 10) {
            boss.vy = 30
        }
    }
    
    function bossAttackAnimation () {
        animation.runImageAnimation(
        boss,
        [img`
            .................ccfff..............
            ................cddbbf..............
            ...............cddbbf...............
            ..............fccbbcf............ccc
            ........ffffffccccccff.........ccbbc
            ......ffbbbbbbbbbbbbbcfff.....cdbbc.
            ....ffbbbbbbbbbcbcbbbbcccff..cddbbf.
            ....fbcbbbbbffbbcbcbbbcccccfffdbbf..
            ....fbbb1111ff1bcbcbbbcccccccbbbcf..
            .....fb11111111bbbbbbcccccccccbccf..
            ......fccc33cc11bbbbccccccccfffbbcf.
            .......fc131c111bbbcccccbdbc...fbbf.
            ........f33c111cbbbfdddddcc.....fbbf
            .........ff1111fbdbbfddcc........fff
            ...........cccccfbdbbfc.............
            .................fffff..............
            `,img`
            .................ccfff..............
            ................cddbbf..............
            ...............cddbbf...............
            .........ffffffccbbcf...............
            ......fffbbbbbbbbcccff..............
            .....fbbbbbbbbbbbbbbbcfff......ccccc
            .....bcbbbbbffbcbcbbbbcccff...cdbbbc
            .....bbb1111ffbbcbcbbbcccccffcddbbc.
            .....fb11111111bcbcbbbcccccccbdbbf..
            ......fccc33c11bbbbbbcccccccccbbcf..
            .......fc131cc11bbbbccccccccffbccf..
            ........f33c1111bbbcccccbdbc..fbbcf.
            .........ff1111cbbbfdddddcc....fbbf.
            ...........ccc1fbdbbfddcc.......fbbf
            ..............ccfbdbbfc..........fff
            .................fffff..............
            `,img`
            ..................ccfff.............
            .................cddbbf.............
            ........fffffffffddbbf..............
            .......fbbbbbbbbbfcbcf..............
            .......fbbc111bffbbccffff...........
            .......fb111111ffbbbbbcccff....ccccc
            ........f1cc3311bbcbcbbccccf..cdbbbc
            ........fcc131c1bbbcbcbcccccfcddbbc.
            .........f111111bbbcbcbccccccbdbbf..
            .........f1111111bbbbbccccccccbbcf..
            ..........f111111bbbbcccccccffbccf..
            ...........c1111cbbbcccccbdbc.fbbcf.
            ............cc11cbbbfddddddc...fbbf.
            ..............cffbdbbfdddcc.....fbbf
            .................fbdbbfcc........fff
            ..................fffff.............
            `,img`
            ....................ccfff...........
            ..........fffffffffcbbbbf...........
            .........fbbbbbbbbbfffbf............
            .........fbb111bffbbbbff............
            .........fb11111ffbbbbbcff..........
            .........f1cccc11bbcbcbcccf.........
            ..........fc1c1c1bbbcbcbcccf...ccccc
            ............c3331bbbcbcbccccfccddbbc
            ...........c333c1bbbbbbbcccccbddbcc.
            ...........c331c11bbbbbcccccccbbcc..
            ..........cc13c111bbbbccccccffbccf..
            ..........c111111cbbbcccccbbc.fccf..
            ...........cc1111cbbbfdddddc..fbbcf.
            .............cccffbdbbfdddc....fbbf.
            ..................fbdbbfcc......fbbf
            ...................fffff.........fff
            `,img`
            ...........fffffff...ccfff..........
            ..........fbbbbbbbffcbbbbf..........
            ..........fbb111bbbbbffbf...........
            ..........fb11111ffbbbbff...........
            ..........f1cccc1ffbbbbbcff.........
            ..........ffc1c1c1bbcbcbcccf........
            ...........fcc3331bbbcbcbcccf..ccccc
            ............c333c1bbbcbcbccccfcddbbc
            ............c333c1bbbbbbbcccccddbcc.
            ............c333c11bbbbbccccccbbcc..
            ...........cc331c11bbbbccccccfbccf..
            ...........cc13c11cbbbcccccbbcfccf..
            ...........c111111cbbbfdddddc.fbbcf.
            ............cc1111fbdbbfdddc...fbbf.
            ..............cccfffbdbbfcc.....fbbf
            ....................fffff........fff
            `,img`
            ....................................
            ....................................
            ....................................
            ...............ccffff...............
            ..............cddbbbf...............
            .......ffffffcddbbbf................
            .....ffbbbbbbbbbbbbbcfff.......ccccc
            ...ffbbbbbbbbcbcbbbbbcccff....cdbbbc
            ..fbbbbbbbbbbcbbcbbbbcccccfffcddbbc.
            .fbcbbbbbbbbbbcbcbbbbccccccccbdbbf..
            .fbbbbbbbfffbbcbbbbbccccccccccbbcf..
            .ffbb1111fffbbcbbbbcccccccbcffbccf..
            ..ff111111111bbbbccccccbbbcc..fbbcf.
            ....ccccccc111bdbbbfddbccc.....ffbbf
            ........ccccccfbdbbbfcc..........fff
            ...............ffffff...............
            `],
        100,
        false
        )
    }

    function bossAngerAttack () {
        bossInvulnerable = true
        bossAttackAnimation()
        cubicbird.moveTowards(boss, playerSprite, 100)
        pause(1000)
        bossInvulnerable = false
        boss.setVelocity(30, 30)
        bossNormalAnimation()
    }

    export function takeDamage(damage : number) :boolean {
        if (!(bossInvulnerable)) {
            sprites.changeDataNumberBy(boss, "hp", -damage)
            cubicbird.displayHitPointBar(sprites.readDataNumber(boss, "hp") / SHARK_MAX_HP * 100)
            if (sprites.readDataNumber(boss, "hp") <= 0) {
                boss.destroy(effects.disintegrate, 2000)
                return true
            } else if (sprites.readDataNumber(boss, "hp") % 3 == 1) {
                bossAngerAttack()
            }
        }
        return false
    }

}